# These are supported funding model platforms

github: [Sycopath]
ko_fi: # Your Ko-fi username
patreon: # Your Patreon username
open_collective: # Your Open Collective username
liberapay: # Your Liberapay username
buymeacoffee: # Your Buy Me a Coffee username

# Custom platforms
# custom: ['https://...']

# Individual sponsors
# github: [username1, username2]
# patreon: [username1, username2]
